### PR TITLE
fix UI icons

### PR DESCRIPTION
**Pull request by mallowigi**
The new release have changed how the icons are assigned in the UI, therefore the workaround @ChrisRM (or whoever did it) found do not work.

This PR hopefully fixes the problem

### CODE REVIEW

**Comment by mallowigi** [comment]
Before:
image

After:
image

**Comment by gayanper** [comment]
The icons in the outline popup for methods are missing.
image

**Comment by mallowigi** [comment]
This is a bug that was prior to my PR.

**Comment by mallowigi** [comment]
@gayanper I fixed it, but it was something that was there previously (and I was used to it TBH)

**Comment by gayanper** [comment]
Now i get the following 
image. Seems like there is still a problem.

**Comment by mallowigi** [comment]
I see, it seems the icons are changing after the project finishes "indexing". Again, this is not a new bug but a very old one, see #257

**Comment by gayanper** [comment]
Seems like the problem is with the iconProvider extension point implementation. Seems like it never gets called for some reason and removing that entry from plugin.xml cause the icons to work for symbols such as methods for example.

**Pull request merged**
