### PR TITLE
Improvements in Java syntax support

### PR DESCRIPTION
**Pull request by kisstkondoros**
fix for https://github.com/ChrisRM/material-theme-jetbrains/issues/39

### CODE REVIEW

**Comment by kisstkondoros** [comment]
Also fixes https://github.com/ChrisRM/material-theme-jetbrains/issues/45

**Comment by b3zman41** [comment]
Please merge ASAP!

**Comment by ChrisRM** [comment]
@b3zman41 Please try now. Download the Material Theme.zip and install it.

**Comment by b3zman41** [comment]
Will do.

**Comment by b3zman41** [comment]
Doesn't look so hot

**Comment by ChrisRM** [comment]
The darker theme isn't ready yet. try the default theme.

**Comment by b3zman41** [comment]
Okay, trying now.

**Comment by b3zman41** [comment]
Looks better, but I think you should open up a .java file in Sublime and try to copy the scheme.

**Comment by ChrisRM** [comment]
Yep, I'll make som improvements there.

**Pull request merged**
