### PR TITLE
Fixes for WebStorm 2017.1

### PR DESCRIPTION
**Pull request by DotNetPart**

### CODE REVIEW

**Comment by denofevil** [comment]
Thanks a lot for the contribution
Fixes #310 and #302

**Comment by denofevil** [comment]
@ChrisRM, can you publish a new version on the plugin site, please?

**Comment by ChrisRM** [comment]
Great job! If anyone can upload a new build, I'll publish the update. I'm don't have IntelliJ on this computer.

**Comment by denofevil** [comment]
@ChrisRM, I'll do this

**Comment by denofevil** [comment]
I've uploaded it [here](https://github.com/ChrisRM/material-theme-jetbrains/releases/tag/0.2.3)

**Comment by denofevil** [comment]
Please hold on, seems like I've found another problem

**Comment by denofevil** [comment]
[This one](https://github.com/ChrisRM/material-theme-jetbrains/releases/tag/v0.2.3.1) should be ok

**Comment by ChrisRM** [comment]
Nice, it's been [updated](https://plugins.jetbrains.com/plugin/8006-material-theme-ui). Should be pushed to the IDE soon I hope! Thanks guys

**Pull request merged**
