### PR TITLE
Refactoring, target IntelliJ 15 (see #226), convert project to Gradle

### PR DESCRIPTION
**Pull request by mjdetullio**
Just cleaning up some of your rookie Java coding.

Also, the Git file rename detection wasn't perfect, but they were renamed correctly.

I converted the project to use https://github.com/JetBrains/gradle-intellij-plugin.  I found that it makes it very easy to target a base IntelliJ version and have the sources attached automatically.  And with Gradle we can ignore the IntelliJ project files in `.idea/`, since they are generated on import from the `build.gradle` file.

### CODE REVIEW

**Comment by mjdetullio** [comment]
ping

**Comment by DevVersion** [comment]
I recently tried to make some personal changes on this repo - It was difficult with all that pushed setup..

Really looking forward to those changes, they look super reasonable.

I personally would not push the `gradlew` script, and instead just mention that Gradle is required to build this project.

**Comment by mjdetullio** [comment]
Committing `gradlew` and the `gradle` directory is a best practice.  It's the only way to set the version of Gradle required to build the project.  Gradle version should be fixed and bumped manually, since Gradle plugins are not compatible with all versions and `build.gradle` syntax can change between versions.

**Comment by DevVersion** [comment]
I personally disagree with that, having a whole wrapper commited to Git, just bloats the repository.

Here are a few reasons about that
> http://stackoverflow.com/a/28473686/4317734

**Comment by ChrisRM** [comment]
Excuse my late response here. I'm going to make some other changes before publishing a new version. Thanks for the work you've put it @mjdetullio 👍

**Pull request merged**
