### PR TITLE
java6 & better dependencies

### PR DESCRIPTION
**Pull request by denofevil**
This makes plugin Java 6 compatible and removes explicit Php dependency to make it work in other IDEs.
Please notice that since project files are not shared in this repo, you'll need to manually specify compiler settings in Project Settings | Project | Project language level - 6

### CODE REVIEW

**Comment by denofevil** [comment]
Closes #10

**Comment by ChrisRM** [comment]
@denofevil By project files you mean the .idea folder? Should I upload that aswell? I'm used to ignoring that for other projects.

**Comment by denofevil** [comment]
@ChrisRM, yep, everything except workspace.xml. Project language level is stored in misc.xml

**Comment by ChrisRM** [comment]
Thanks, I'll be sure to commit that later today.

**Pull request merged**
