### PR TITLE
Darker and default theme improvements and better Java icon support

### PR DESCRIPTION
**Pull request by kisstkondoros**

### CODE REVIEW

**Comment by kisstkondoros** [comment]
fix for https://github.com/ChrisRM/material-theme-jetbrains/issues/53 in second and third commit

**Comment by kisstkondoros** [comment]
fix for https://github.com/ChrisRM/material-theme-jetbrains/issues/56

**Comment by vitorprado** [comment]
:+1:
gradle and java files use some dark keywords in both themes.. I think this will solve this problem. :heart:

**Comment by ChrisRM** [comment]
Couldn't merge this, but I added the psi association and java icons. Thanks @kisstkondoros

**Pull request closed without merging**
